### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by bernardobarreto** [comment]
Best thread comment: "Is it at all ironic that this got merged into master?"

**Comment by mehulkar** [comment]
Wow, this is awesome. Can you rebase though!

**Comment by mehulkar** [comment]
@Kikobeats can you rebase (or I can just add this in myself) I don't know how to rebase someone else's pull request.

**Comment by Kikobeats** [comment]
is yet in your repo! ;-)

**Comment by mehulkar** [comment]
Oh oops cool :)

**Pull request closed without merging**
