### PR TITLE
Recruiter looking for a developer with "strong LAMP background" results in thread full of LAMP stacks

### PR DESCRIPTION
**Pull request by jnv**
Not sure where to post this, since the original issue is not relevant and it is not the comment, but the reaction what makes this epic.

### CODE REVIEW

**Comment by jipiboily** [comment]
Hehe, that recruiter's account doesn't even exists anymore, neither his/her account :)

There are some nice lamps though.

**Comment by vendethiel** [comment]
Too bad the message disappeared :P.

**Comment by jnv** [comment]
Oh, shame on them! There is a backup:
https://github.com/thoughtbot/liftoff/pull/178#issuecomment-57768157
Anyway, should I close this PR or do you think it is hall-of-fame worthy?

**Comment by vendethiel** [comment]
As for myself, I believe it's worthy – but I would include the image

**Comment by mehulkar** [comment]
Haha, I think that entire thread is worthy. @jnv want to add it as an issue instead of a comment?

**Comment by jnv** [comment]
@mehulkar Sure; should I add the comments' screenshot too or just leave the content as it is?

**Comment by mehulkar** [comment]
Just the whole thread is fine. You can make the title text a little descriptive about what it is :)

**Comment by jnv** [comment]
Okay, here you go @mehulkar. I've moved this under issues, changed the link to a [first related comment](https://github.com/thoughtbot/liftoff/pull/178#issuecomment-57690259) and changed description to:

> In an unrelated thread recruiter asks for a developer with “strong LAMP background,” receives photos showing lamp stacking skills.

**Pull request merged**
