### PR TITLE
PR that introduced the Heartbleed bug

### PR DESCRIPTION
**Pull request by davinov**

### CODE REVIEW

**Comment by mehulkar** [comment]
Ooh, less funny, but pretty epic. Can you rebase?

**Comment by davinov** [comment]
Done

**Comment by mehulkar** [comment]
Oh no @davinov I got to this after the other ones, so it needs another rebase :(

**EDIT** Updated the format so there won't be merge conflicts anymore :)
Sorry and thank you for resubmitting! See #13

**Comment by davinov** [comment]
@mehulkar No problem ;)
Done!

What about github-pages for the website. What do you think?

**Comment by mehulkar** [comment]
@davinov yes, that's the plan! See #15

**Pull request merged**
