### PR TITLE
Added proposed entry

### PR DESCRIPTION
**Pull request by kevin-hanselman**
Proposing [this pull request](https://github.com/esneider/YUNOcommit.vim/pull/6).

### CODE REVIEW

**Comment by mehulkar** [comment]
@kevlar1818 thanks for the submission. Why is this hall of fame worthy?

**Comment by kevin-hanselman** [comment]
Ridiculous? Funny? Ridiculously funny?

**Comment by mehulkar** [comment]
It's got a bit of mirth to it. But I'm not sold on it's epicness. After all there are probably thousands of pull requests with ascii art that is amusing. Sorry @kevlar1818!

**Comment by kevin-hanselman** [comment]
I understand. No worries!

**Pull request closed without merging**
