### PR TITLE
Add swift's original commit

### PR DESCRIPTION
**Pull request by vendethiel**
This is only a valid submission if judging by the number of comments, of course :-).

### CODE REVIEW

**Comment by mehulkar** [comment]
heh, let's give it a day to breathe before inducting into any halls :)

i'm not sure how epic it is though. it's really the same as the first commit of any other language

**Comment by vendethiel** [comment]
Yep -- hence my comment

**Comment by vendethiel** [comment]
okay, I think this one might be much better: https://github.com/apple/swift/pull/17

**Comment by jomo** [comment]
Yes, I was about to suggest apple/swift#17.
It's much more hilarious, and the fact that it's the _very first_ public Pull Request makes it even better.

**Pull request closed without merging**
