### PR TITLE
Jim Weirich's tribute thread

### PR DESCRIPTION
**Pull request by holman**
This spontaneous thread always felt so fitting.

### CODE REVIEW

**Comment by achalv** [comment]
I was just about to fork this repo and submit a PR with the Jim Weirich tribute thread, but I was having trouble finding it.
Thanks, @holman!

**Comment by zzz6519003** [comment]
simultaneously! 
actually i'm curious how do u find this repo @holman

**Comment by caarlos0** [comment]
+1 :heart:

**Comment by tejasbubane** [comment]
I was just about to fork and submit this tribute link. So spontaneous.

**Comment by bernardobarreto** [comment]
:cry:

**Comment by joerocklin** [comment]
+1

**Pull request merged**
