### PR TITLE
A very nice commit, added

### PR DESCRIPTION
**Pull request by elbrujohalcon**
by @ronchifabricio

### CODE REVIEW

**Comment by jomo** [comment]
That repo has 2 stars, 6 commits, 0 issues, and no comments.
:-1: I don't see why this should go to a 'Hall of Fame', sorry.

**Comment by elbrujohalcon** [comment]
@jomo because it's pure github magic… the author had a repo with his goals for this year… and he basically replaced them all by a single **To Be Happy!** statement.
That commit is _poetry_, it's not your regular commit.

**Comment by hugoabonizio** [comment]
:+1:

**Comment by elbrujohalcon** [comment]
This PR is a bit old, I think I'll just close it :trollface:

**Pull request closed without merging**
